In [2]:
import numpy as np

In [2]:
demo = np.array([1,2,3,4])
print(demo)
print(demo.ndim)

[1 2 3 4]
1


In [3]:
demo = np.array([[1,2,3,4]])
print(demo)
print(demo.ndim)

[[1 2 3 4]]
2


In [4]:
demo = np.array([[1,2,3,'a']])
print(demo)
print(demo.ndim)

[['1' '2' '3' 'a']]
2


In [5]:
demo = np.array([[1,2,3,4],[5,6,7,8]])
print(demo)
print(demo.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [6]:
demo = np.array([[[1]]])
print(demo)
print(demo.ndim)

[[[1]]]
3


In [7]:
demo = np.array([[1,2,3,4],[5,6,7,8]])
print(demo[0][2])
print(demo.ndim)

3
2


In [8]:
a5 = np.zeros((3,4))
a5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
a5 = np.full((3,4),"Hello")
a5

array([['Hello', 'Hello', 'Hello', 'Hello'],
       ['Hello', 'Hello', 'Hello', 'Hello'],
       ['Hello', 'Hello', 'Hello', 'Hello']], dtype='<U5')

In [10]:
demo = np.array([[1,2,3,4],[5,6,7,8]])
demo = np.insert(demo,2,50)
print(demo)

[ 1  2 50  3  4  5  6  7  8]


In [11]:
demo = np.array([[1,2,3,4],[5,6,7,8]])
demo = np.insert(demo,2,50,axis = 1)
print(demo)

[[ 1  2 50  3  4]
 [ 5  6 50  7  8]]


In [12]:
demo = np.array([[1,2,3,4],[5,6,7,8]])
demo = np.insert(demo,2,50,axis = 0)
demo

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [50, 50, 50, 50]])

In [13]:
demo = np.array([[1,2,3,4],[5,6,7,8]])
demo = np.delete(demo,1,axis = 1)
print(demo)

[[1 3 4]
 [5 7 8]]


In [14]:
demo = np.array([[1,2,3,4],[5,6,7,8]])
demo = np.delete(demo,1,axis = 0)
print(demo)

[[1 2 3 4]]


In [15]:
demo = np.array([[1,2,3,4],[5,6,7,8]])
demo1 = np.copy(demo)
print(demo1)
demo2 = demo.copy()
print(demo2)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [16]:
demo = np.array([5,6,7,8,1,2,3,4])
demo1 = np.sort(demo)
print(demo1)
demo.sort()
print(demo)

[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]


In [17]:
demo = np.array([5,6,7,8,1,2,3,4])
demo1 = np.sort(demo)
r = demo1[::-1]
r

array([8, 7, 6, 5, 4, 3, 2, 1])

In [18]:
demo = np.array([[5,7,6,8],[1,3,2,4]])
demo1 = np.sort(demo)[:,::-1]
demo1

array([[8, 7, 6, 5],
       [4, 3, 2, 1]])

In [19]:
demo = np.array([[5,7,6,8],[1,3,2,4],[29,43,56,32]])
demo1 = np.array([[1,3,2,4],[29,43,56,32],[5,7,6,8]])
np.vstack([demo,demo1])

array([[ 5,  7,  6,  8],
       [ 1,  3,  2,  4],
       [29, 43, 56, 32],
       [ 1,  3,  2,  4],
       [29, 43, 56, 32],
       [ 5,  7,  6,  8]])

In [20]:
demo = np.array([[5,7,6,8],[1,3,2,4],[29,43,56,32]])
demo1 = np.array([[1,3,2,4],[29,43,56,32],[5,7,6,8]])
np.hstack([demo,demo1])

array([[ 5,  7,  6,  8,  1,  3,  2,  4],
       [ 1,  3,  2,  4, 29, 43, 56, 32],
       [29, 43, 56, 32,  5,  7,  6,  8]])

In [21]:
demo = np.array([[5,7,6,8],[1,3,2,4],[29,43,56,32]])
demo1 = np.array([[1,3,2,4],[29,43,56,32],[5,7,6,8]])
np.ravel([demo])

array([ 5,  7,  6,  8,  1,  3,  2,  4, 29, 43, 56, 32])

In [22]:
demo = np.array([[5,7,6,8],[1,3,2,4],[29,43,56,32]])
demo1 = np.array([[1,3,2,4],[29,43,56,32],[5,7,6,8]])
np.ravel([demo,demo1])

array([ 5,  7,  6,  8,  1,  3,  2,  4, 29, 43, 56, 32,  1,  3,  2,  4, 29,
       43, 56, 32,  5,  7,  6,  8])

In [23]:
demo = np.array([[5,7,6,8],[1,3,2,4],[29,43,56,32]])
demo1 = np.array([[1,3,2,4],[29,43,56,32],[5,7,6,8]])
np.concatenate([demo,demo1], axis = 0)

array([[ 5,  7,  6,  8],
       [ 1,  3,  2,  4],
       [29, 43, 56, 32],
       [ 1,  3,  2,  4],
       [29, 43, 56, 32],
       [ 5,  7,  6,  8]])

In [24]:
demo = np.array([[5,7,6,8],[1,3,2,4],[29,43,56,32]])
demo1 = np.array([[1,3,2,4],[29,43,56,32],[5,7,6,8]])
np.concatenate([demo,demo1], axis = 1)

array([[ 5,  7,  6,  8,  1,  3,  2,  4],
       [ 1,  3,  2,  4, 29, 43, 56, 32],
       [29, 43, 56, 32,  5,  7,  6,  8]])

In [25]:
an_array = np.genfromtxt(r"/data/Coding_Shennanigans/TechMindz/TM_AI/Dir_Test/Test.txt")
print(an_array)

[ 100. 1000.   10. 6000.]


In [26]:
print(an_array.dtype)

float64


In [27]:
type(an_array)

numpy.ndarray

In [28]:
print(an_array>500)

[False  True False  True]


In [29]:
print(an_array==500)

[False False False False]


In [30]:
print(np.all(an_array>500))

False


In [31]:
print(np.any(an_array>500))

True


In [34]:
print(an_array[an_array>500])

[1000. 6000.]


In [37]:
print(an_array[(an_array>500) & (an_array<2000)])

[1000.]


In [39]:
print(an_array[an_array%2 == 0])

[ 100. 1000.   10. 6000.]


In [40]:
a= np.array([1,2,3])
b= np.array([1,2,3])
print(np.equal(a,b))
print(np.array_equal(a,b))

[ True  True  True]
True


In [45]:
aa = np.array([1,2,3,4,5,6,7,8])
print(np.split(aa,4))

ab = np.array([1,2,3,4,5,6,7,8])
print(np.array_split(aa,5))

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7]), array([8])]


In [47]:
aaa = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.split(aaa,3,axis = 0))

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [48]:
aaa = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.split(aaa,3,axis = 1))

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [51]:
out = np.random.random(5)
out

array([0.76557637, 0.3051485 , 0.33889241, 0.57006617, 0.47062887])

In [54]:
out = np.random.randint(2,100,5)
out

array([80, 53, 93, 60, 30])

In [57]:
abc = np.arange(100)
print(abc)
print(abc.size)
print(abc.itemsize)
print(abc.dtype)
print(abc.nbytes)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
100
8
int64
800


In [59]:
a = np.array([2,5,6,7,])
print(a[0])
print(a[0:])
print(a[:2])
print(a[1:3])

2
[2 5 6 7]
[2 5]
[5 6]


In [60]:
a = np.array([2,5,6,7,])
print(a+2)
print(a-3)
print(a/4)
print(a*5)

[4 7 8 9]
[-1  2  3  4]
[0.5  1.25 1.5  1.75]
[10 25 30 35]


In [3]:
np.subtract(5,3)

np.int64(2)

In [4]:
np.divide(5,3)

np.float64(1.6666666666666667)

In [5]:
np.multiply(5,3)

np.int64(15)

In [6]:
np.sqrt(5)


np.float64(2.23606797749979)

In [7]:
aaa0 = np.array([[1,2,3],[4,5,6],[7,8,9]])
aaa1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.subtract(aaa0,aaa1))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [8]:
print(np.divide(aaa0,aaa1))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
print(np.multiply(aaa0,aaa1))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [10]:
print(np.sqrt(aaa0))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [11]:
f = np.linspace(1,7,4)
print(f)

[1. 3. 5. 7.]


In [16]:
aaa0 = np.array([1,2,3,4,5,6])

reshaped_arr = aaa0.reshape (2,3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]
